# Generated by Django 5.0.1 on 2024-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('analyzed_text', models.TextField(blank=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
